/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigo;

import com.sun.beans.TypeResolver;
import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Polygon;
import java.awt.image.BufferedImage;
import javafx.scene.transform.Transform;



/**
 *
 * @author Pablo
 */
public class VentanaPaint extends javax.swing.JFrame {

    //Para guardar una imagen en la memoria
    BufferedImage buffer = null;
    BufferedImage buffer2 = null;
    

    int valoresX[] = { 260, 210, 230, 290, 310 };
       int valoresY[] = { 30, 70, 120, 120, 70 };
       Polygon poligono1 = new Polygon( valoresX, valoresY, 5 );
   
    
   Graphics2D bufferGraphics, buffer2Graphics, lienzoGraphics = null; 
    
    
    Color colorSeleccionado = Color.blue;
   
    int formaSeleccionada = 0;
    
    Circulo miCirculo ;
    Cuadrado miCuadrado;
    Rombo miRombo;
    Triangulo miTriangulo;
     Pentagono miPentagono;
   Hexagono miHexagono;
     
    public VentanaPaint() {
        initComponents();
        inicializaBuffers();
        jDialog1.setSize(600,400);
        
    }

    //Confirmacion de que queremos cambiar el codigo de la clase madre de java
    @Override
    public void paint(Graphics g){
        //Ejecuta el codigo de madre paint de JFrame
       super.paint(g);
       

        //Dibuja el buffer en el JPanel
        lienzoGraphics.drawImage(buffer, 0, 0, null);
        
       
    }
    

     
    private void inicializaBuffers(){
        lienzoGraphics = (Graphics2D)lienzo.getGraphics();
        //Creo una imagen del mismo ancho y alto que el lienzo
        //Casteo--> BufferedImage
        buffer = (BufferedImage)lienzo.createImage(lienzo.getWidth(), lienzo.getHeight());
        //Creo una imagen modificable
        bufferGraphics = buffer.createGraphics();
        //Dibujamos un rectangulo blanco del tamaño del lienzo
        bufferGraphics.setColor(Color.white);
        bufferGraphics.fillRect(0, 0, buffer.getWidth(), buffer.getHeight());
        
      
        //Inicializo el 2 buffer
        buffer2 = (BufferedImage)lienzo.createImage(lienzo.getWidth(), lienzo.getHeight());
        //Creo una imagen modificable
        buffer2Graphics = buffer2.createGraphics();
        //Dibujamos un rectangulo blanco del tamaño del lienzo
        buffer2Graphics.setColor(Color.white);
        buffer2Graphics.fillRect(0, 0, buffer2.getWidth(), buffer2.getHeight());
        
      
        
        
        
    }
    
    
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jColorChooser1 = new javax.swing.JColorChooser();
        botonCancelar = new javax.swing.JButton();
        botonAceptar = new javax.swing.JButton();
        lienzo = new javax.swing.JPanel();
        color = new javax.swing.JButton();
        circulo = new javax.swing.JButton();
        cuadrado = new javax.swing.JButton();
        rombo = new javax.swing.JButton();
        triangulo = new javax.swing.JButton();
        borrar = new javax.swing.JButton();
        pentagono = new javax.swing.JButton();
        hexagono = new javax.swing.JButton();

        jColorChooser1.setSize(new java.awt.Dimension(600, 400));

        botonCancelar.setText("Cancelar");
        botonCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonCancelarMousePressed(evt);
            }
        });

        botonAceptar.setText("Aceptar");
        botonAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonAceptarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addComponent(jColorChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(botonAceptar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonCancelar)
                .addGap(148, 148, 148))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addComponent(jColorChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCancelar)
                    .addComponent(botonAceptar))
                .addGap(0, 29, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lienzo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lienzoMouseDragged(evt);
            }
        });
        lienzo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lienzoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lienzoMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout lienzoLayout = new javax.swing.GroupLayout(lienzo);
        lienzo.setLayout(lienzoLayout);
        lienzoLayout.setHorizontalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        lienzoLayout.setVerticalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 218, Short.MAX_VALUE)
        );

        color.setText("Color");
        color.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                colorMousePressed(evt);
            }
        });

        circulo.setText("Circulo");
        circulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                circuloMousePressed(evt);
            }
        });

        cuadrado.setText("Cuadrado");
        cuadrado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cuadradoMousePressed(evt);
            }
        });

        rombo.setText("Rombo");
        rombo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                romboMousePressed(evt);
            }
        });

        triangulo.setText("Triangulo");
        triangulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                trianguloMousePressed(evt);
            }
        });

        borrar.setText("Borrar");
        borrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                borrarMousePressed(evt);
            }
        });

        pentagono.setText("Pentagono");
        pentagono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pentagonoMousePressed(evt);
            }
        });

        hexagono.setText("Hexagono");
        hexagono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                hexagonoMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lienzo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(circulo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rombo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(triangulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(color, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(borrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pentagono)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hexagono)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(color, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(circulo)
                    .addComponent(cuadrado)
                    .addComponent(rombo)
                    .addComponent(triangulo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(borrar)
                    .addComponent(pentagono)
                    .addComponent(hexagono))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lienzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lienzoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lienzoMousePressed
       //evt te dice donde has pulsado
       switch(formaSeleccionada){
          case 0:
             miCirculo = new Circulo(evt.getX(), evt.getY(), 10, colorSeleccionado, false); 
             miCirculo.dibujate(bufferGraphics, evt.getX());
             break;
          case 1:
             miCuadrado = new Cuadrado(evt.getX(), evt.getY(), 10, colorSeleccionado, true);
             miCuadrado.dibujate(bufferGraphics, evt.getX());
             break;
          case 2:
              miRombo = new Rombo (evt.getX(), evt.getY(), 10, 5,  colorSeleccionado, true);
              miRombo.dibujate(bufferGraphics, evt.getX());
      
              break;
          case 3: 
              miTriangulo = new Triangulo (evt.getX(), evt.getY(), 10, colorSeleccionado, true);
              miTriangulo.dibujate(bufferGraphics, evt.getX());
              break;
               
//          case 4: //De prueba borrador intenta pintar el lienzo de blanco
//              lienzoGraphics.setColor(Color.WHITE);
//              buffer2Graphics.setColor(Color.WHITE);
         
         
//          case 5:  //De prueba arrays con valores asignados           
//              bufferGraphics.setPaint(Color.MAGENTA);
//              bufferGraphics.drawPolygon(poligono1);
//              break;
       
        case 6: 
          
              miPentagono = new Pentagono(evt.getX(), evt.getY(), new int[5], new int[5], colorSeleccionado, true); 
             
              break;  
              
        case 7: 
          
              miHexagono = new Hexagono(evt.getX(), evt.getY(), new int[6], new int[6], colorSeleccionado, true); 
             
              break;
       
      }        
        //0, 0 de la posicion y 1, 1 
        repaint(0, 0, 1, 1);
    }//GEN-LAST:event_lienzoMousePressed

    private void lienzoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lienzoMouseDragged
        
      
  

        /*Borro lo que hubiera en el lienzo
        g2.setColor(Color.white);
        g2.fillRect(0, 0, buffer.getWidth(), buffer.getHeight());
        */  
        
        bufferGraphics.drawImage(buffer2, 0, 0, null);

        
        switch(formaSeleccionada){
           case 0:
              miCirculo.dibujate(bufferGraphics, evt.getX());
              break;
           case 1:          
              miCuadrado.dibujate(bufferGraphics, evt.getX());
              break;
           case 2:
              miRombo.dibujate(bufferGraphics, evt.getX());
              miRombo.redimension(evt.getX(), evt.getY());
              break;
           case 3: 
              miTriangulo.dibujate(bufferGraphics, evt.getX());
              miTriangulo.redimension(evt.getX());
              break;
              
//           case 5:  //De prueba arrays con valores asignados
//              bufferGraphics.setPaint(Color.RED);
//              bufferGraphics.drawPolygon(poligono1);
//              break; 
              
              
           case 6: 
               
              miPentagono.dibujate(bufferGraphics, evt.getY());
              break;
  
           case 7: 
               
              miHexagono.dibujate(bufferGraphics, evt.getY());
              break;
               

       
      }
        
 
      
        
        bufferGraphics.drawImage(buffer, 0, 0, null);
        //0, 0 de la posicion y 1, 1 
        repaint(0, 0, 1, 1);
    }//GEN-LAST:event_lienzoMouseDragged

    private void lienzoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lienzoMouseReleased
        //Realased detecta que el raton suelta el objeto
       
        
      switch(formaSeleccionada){
          case 0:
             miCirculo.dibujate(buffer2Graphics, evt.getX());
             break;
          case 1:
             miCuadrado.dibujate(buffer2Graphics, evt.getX());
             break;
          case 2:
             miRombo.dibujate(buffer2Graphics, evt.getX());
              
             break;
          case 3: 
             miTriangulo.dibujate(buffer2Graphics, evt.getX());
             
//          case 4: //De prueba borrador intenta pintar el lienzo de blanco
//             lienzoGraphics.setColor(Color.WHITE);
//             buffer2Graphics.setColor(Color.WHITE);
              
//          case 5:  //De prueba arrays con valores asignados
//             bufferGraphics.setPaint(Color.MAGENTA);
//             buffer2Graphics.drawPolygon(poligono1);
//             break;
       
          case 6: 
 
             miPentagono.dibujate(buffer2Graphics, evt.getY());
             break;
          case 7: 
 
             miHexagono.dibujate(buffer2Graphics, evt.getY());
             break;
       
       
      }    
        
    }//GEN-LAST:event_lienzoMouseReleased

    private void colorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colorMousePressed
       jDialog1.setVisible(true);
    }//GEN-LAST:event_colorMousePressed

    private void botonAceptarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAceptarMousePressed
        colorSeleccionado = jColorChooser1.getColor();
        jDialog1.setVisible(false);
    }//GEN-LAST:event_botonAceptarMousePressed

    private void botonCancelarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCancelarMousePressed
       //TO DO
    }//GEN-LAST:event_botonCancelarMousePressed

    private void circuloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_circuloMousePressed
        formaSeleccionada = 0;
    }//GEN-LAST:event_circuloMousePressed

    private void cuadradoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuadradoMousePressed
       formaSeleccionada = 1;
    }//GEN-LAST:event_cuadradoMousePressed

    private void romboMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_romboMousePressed
        formaSeleccionada = 2;
    }//GEN-LAST:event_romboMousePressed

    private void trianguloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trianguloMousePressed
        formaSeleccionada = 3;
    }//GEN-LAST:event_trianguloMousePressed

    private void borrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_borrarMousePressed

    private void pentagonoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pentagonoMousePressed
        formaSeleccionada = 6;
    }//GEN-LAST:event_pentagonoMousePressed

    private void hexagonoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hexagonoMousePressed
        formaSeleccionada = 7;
    }//GEN-LAST:event_hexagonoMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPaint().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrar;
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton circulo;
    private javax.swing.JButton color;
    private javax.swing.JButton cuadrado;
    private javax.swing.JButton hexagono;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JPanel lienzo;
    private javax.swing.JButton pentagono;
    private javax.swing.JButton rombo;
    private javax.swing.JButton triangulo;
    // End of variables declaration//GEN-END:variables
}
